<a href="https://colab.research.google.com/github/calinvlt/numpy-basics/blob/main/NumPy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Dot product operation using a regular loop

In [20]:
def python_forloop_list_approach(x, w):
  z = 0.
  for i in range(len(x)):
      z += x[i] * w[i]
  return z

a = [1., 2., 3.]
b = [4., 5., 6.]

print(python_forloop_list_approach(a, b))

large_a = list(range(1000))
large_b = list(range(1000))

%timeit python_forloop_list_approach(large_a, large_b)

32.0
84.2 µs ± 10.1 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Dot product operation using numpy operation

In [22]:
import numpy as np

def numpy_dotproduct_approach(a, b):
  return a.dot(b)

n_a = np.array(a)
n_b = np.array(b)

print(numpy_dotproduct_approach(np.array(a), np.array(b)))

n_large_a = np.array(large_a)
n_large_b = np.array(large_b)

%timeit numpy_dotproduct_approach(n_large_a, n_large_b)

32.0
1.84 µs ± 464 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


N-dimensional array

In [28]:
lst = [[1., 2., 3.], [4., 5., 6.]]
array2d = np.array(lst)
array2d[1,2]


np.float64(6.0)

In [27]:
array2d.ndim

2

In [29]:
array2d.shape

(2, 3)

Array construction

In [31]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
np.zeros((2, 4), dtype=np.int8)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [35]:
np.zeros((2, 4), dtype=np.int8) + 99

array([[99, 99, 99, 99],
       [99, 99, 99, 99]], dtype=int8)

In [37]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
np.empty((4,5))

array([[0. , 0. , 0.3, 1. , 0. ],
       [0. , 1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 0. , 0. ],
       [1. , 0.5, 0. , 0. , 1. ]])

In [40]:
np.diag((1, 2))

array([[1, 0],
       [0, 2]])

In [43]:
np.arange(2, 50, 10)

array([ 2, 12, 22, 32, 42])

In [47]:
np.linspace(0., 1., num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])